#ifndef DHCP_PACKET_H
#define DHCP_PACKET_H

/**
* file: packet.h
* This file contains the definitions of what makes the DHCP packet. 
* Also found here are the procedures necessary for handling these packets to byte streams and structs and vice versa.
*/

#include <iostream>
#include <unordered_map>
#include <vector>

/**
 * dhcp_header
 *
 * WARNING: this model stores data in host order. all helper functions serializing this data to a buffer must 
 *          perform network to host byte order and vice versa.
 *
 * we define a struct for the dhcp header that is packed, meaning that we avoid any forms of padding 
 * created by the compiler during compile-time. this is to strictly adhere to the formatting in the
 * byte buffer when we send the data in between hosts via sockets.
 */
struct __attribute__((packed)) dhcp_header {
    uint8_t     op;             // Type of operation: 1 = BOOTREQUEST, 2 = BOOTREPLY
    uint8_t     htype;          // Hardware type: 1 = Ethernet
    uint8_t     hlen;           // Hardware address length: 6 bytes
    uint8_t     hops;           // 0 since no helper address
    uint32_t    xid;            // Generated by client, used by server for state tracking
    uint16_t    secs;           // Lease time as a 16-bit unsigned integer
    uint16_t    flags;          // 0 for unicast server reply, 1 for broadcast client discovery
    uint32_t    ciaddr;         // Client IP, 0.0.0.0 for discovery
    uint32_t    yiaddr;         // Leased address from server
    uint32_t    siaddr;         // Next server for bootstrap server
    uint32_t    giaddr;         // Gateway address for the end hosts
    uint8_t     chaddr[16];     // Client MAC address
    uint8_t     sname[64];      // Server hostname, all 0 if unused
    uint8_t     file[128];      // Directory and path of the boot file
    uint32_t    magic_cookie;   // 0x63825363
};

/**
  * dhcp_packet
  *
  * this class contains the structured DHCP packet complete with the fixed header and variable options field.
  * we define the options field as an unordered map in software. We map the possible option types to the corresponding values.
  * take note that the options field utilizes the TLV (type-length-value) format. 
  */

class dhcp_packet {
public:
  struct dhcp_header                                  header; // contains fixed header 
  std::unordered_map<uint8_t, std::vector<uint8_t> >  options;

  void build_header(uint8_t op, uint32_t xid, uint16_t secs, uint16_t flags,
                    uint32_t ciaddr, uint32_t yiaddr, uint32_t siaddr,
                    uint32_t giaddr, uint8_t chaddr[16]);

  void preflight_order_change();

  ssize_t serialize(uint8_t buf[], size_t max_len);
  ssize_t deserialize(uint8_t buf[], size_t bytes_received);
};
 

#endif 
